/*
 * Italian eInvoice API
 * The Italian eInvoice API is a RESTful API that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed by Invoicetronic to be simple and easy to use, abstracting away SDI complexity while still providing complete control over the invoice send/receive process. The API also provides advanced features and a rich toolchain, such as invoice validation, multiple upload methods, webhooks, event logs, CORS support, client SDKs for commonly used languages, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.invoicetronic.invoice.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.invoicetronic.invoice.sdk.model.DatiBollo;
import com.invoicetronic.invoice.sdk.model.DatiCassaPrevidenziale;
import com.invoicetronic.invoice.sdk.model.DatiRitenuta;
import com.invoicetronic.invoice.sdk.model.ScontoMaggiorazione;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DatiGeneraliDocumento
 */
public class DatiGeneraliDocumentoTest {
    private final DatiGeneraliDocumento model = new DatiGeneraliDocumento();

    /**
     * Model tests for DatiGeneraliDocumento
     */
    @Test
    public void testDatiGeneraliDocumento() {
        // TODO: test DatiGeneraliDocumento
    }

    /**
     * Test the property 'tipoDocumento'
     */
    @Test
    public void tipoDocumentoTest() {
        // TODO: test tipoDocumento
    }

    /**
     * Test the property 'divisa'
     */
    @Test
    public void divisaTest() {
        // TODO: test divisa
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'numero'
     */
    @Test
    public void numeroTest() {
        // TODO: test numero
    }

    /**
     * Test the property 'datiRitenuta'
     */
    @Test
    public void datiRitenutaTest() {
        // TODO: test datiRitenuta
    }

    /**
     * Test the property 'datiBollo'
     */
    @Test
    public void datiBolloTest() {
        // TODO: test datiBollo
    }

    /**
     * Test the property 'datiCassaPrevidenziale'
     */
    @Test
    public void datiCassaPrevidenzialeTest() {
        // TODO: test datiCassaPrevidenziale
    }

    /**
     * Test the property 'scontoMaggiorazione'
     */
    @Test
    public void scontoMaggiorazioneTest() {
        // TODO: test scontoMaggiorazione
    }

    /**
     * Test the property 'importoTotaleDocumento'
     */
    @Test
    public void importoTotaleDocumentoTest() {
        // TODO: test importoTotaleDocumento
    }

    /**
     * Test the property 'arrotondamento'
     */
    @Test
    public void arrotondamentoTest() {
        // TODO: test arrotondamento
    }

    /**
     * Test the property 'causale'
     */
    @Test
    public void causaleTest() {
        // TODO: test causale
    }

    /**
     * Test the property 'art73'
     */
    @Test
    public void art73Test() {
        // TODO: test art73
    }

}
