/*
 * Invoicetronic API
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: support@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.invoicetronic.invoice.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DatiConvenzione
 */
public class DatiConvenzioneTest {
    private final DatiConvenzione model = new DatiConvenzione();

    /**
     * Model tests for DatiConvenzione
     */
    @Test
    public void testDatiConvenzione() {
        // TODO: test DatiConvenzione
    }

    /**
     * Test the property 'riferimentoNumeroLinea'
     */
    @Test
    public void riferimentoNumeroLineaTest() {
        // TODO: test riferimentoNumeroLinea
    }

    /**
     * Test the property 'idDocumento'
     */
    @Test
    public void idDocumentoTest() {
        // TODO: test idDocumento
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'numItem'
     */
    @Test
    public void numItemTest() {
        // TODO: test numItem
    }

    /**
     * Test the property 'codiceCommessaConvenzione'
     */
    @Test
    public void codiceCommessaConvenzioneTest() {
        // TODO: test codiceCommessaConvenzione
    }

    /**
     * Test the property 'codiceCup'
     */
    @Test
    public void codiceCupTest() {
        // TODO: test codiceCup
    }

    /**
     * Test the property 'codiceCig'
     */
    @Test
    public void codiceCigTest() {
        // TODO: test codiceCig
    }

}
