/*
 * Invoicetronic API
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: info@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.invoicetronic.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.invoicetronic.sdk.model.Anagrafica;
import com.invoicetronic.sdk.model.IdFiscaleIVA;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.invoicetronic.sdk.JSON;

/**
 * DatiAnagraficiVettore
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-17T10:18:31.150718Z[Etc/UTC]", comments = "Generator version: 7.14.0")
public class DatiAnagraficiVettore implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID_FISCALE_IVA = "id_fiscale_iva";
  @SerializedName(SERIALIZED_NAME_ID_FISCALE_IVA)
  @javax.annotation.Nullable
  private IdFiscaleIVA idFiscaleIva;

  public static final String SERIALIZED_NAME_CODICE_FISCALE = "codice_fiscale";
  @SerializedName(SERIALIZED_NAME_CODICE_FISCALE)
  @javax.annotation.Nullable
  private String codiceFiscale;

  public static final String SERIALIZED_NAME_ANAGRAFICA = "anagrafica";
  @SerializedName(SERIALIZED_NAME_ANAGRAFICA)
  @javax.annotation.Nullable
  private Anagrafica anagrafica;

  public static final String SERIALIZED_NAME_NUMERO_LICENZA_GUIDA = "numero_licenza_guida";
  @SerializedName(SERIALIZED_NAME_NUMERO_LICENZA_GUIDA)
  @javax.annotation.Nullable
  private String numeroLicenzaGuida;

  public DatiAnagraficiVettore() {
  }

  public DatiAnagraficiVettore idFiscaleIva(@javax.annotation.Nullable IdFiscaleIVA idFiscaleIva) {
    this.idFiscaleIva = idFiscaleIva;
    return this;
  }

  /**
   * Get idFiscaleIva
   * @return idFiscaleIva
   */
  @javax.annotation.Nullable
  public IdFiscaleIVA getIdFiscaleIva() {
    return idFiscaleIva;
  }

  public void setIdFiscaleIva(@javax.annotation.Nullable IdFiscaleIVA idFiscaleIva) {
    this.idFiscaleIva = idFiscaleIva;
  }


  public DatiAnagraficiVettore codiceFiscale(@javax.annotation.Nullable String codiceFiscale) {
    this.codiceFiscale = codiceFiscale;
    return this;
  }

  /**
   * Get codiceFiscale
   * @return codiceFiscale
   */
  @javax.annotation.Nullable
  public String getCodiceFiscale() {
    return codiceFiscale;
  }

  public void setCodiceFiscale(@javax.annotation.Nullable String codiceFiscale) {
    this.codiceFiscale = codiceFiscale;
  }


  public DatiAnagraficiVettore anagrafica(@javax.annotation.Nullable Anagrafica anagrafica) {
    this.anagrafica = anagrafica;
    return this;
  }

  /**
   * Get anagrafica
   * @return anagrafica
   */
  @javax.annotation.Nullable
  public Anagrafica getAnagrafica() {
    return anagrafica;
  }

  public void setAnagrafica(@javax.annotation.Nullable Anagrafica anagrafica) {
    this.anagrafica = anagrafica;
  }


  public DatiAnagraficiVettore numeroLicenzaGuida(@javax.annotation.Nullable String numeroLicenzaGuida) {
    this.numeroLicenzaGuida = numeroLicenzaGuida;
    return this;
  }

  /**
   * Get numeroLicenzaGuida
   * @return numeroLicenzaGuida
   */
  @javax.annotation.Nullable
  public String getNumeroLicenzaGuida() {
    return numeroLicenzaGuida;
  }

  public void setNumeroLicenzaGuida(@javax.annotation.Nullable String numeroLicenzaGuida) {
    this.numeroLicenzaGuida = numeroLicenzaGuida;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatiAnagraficiVettore datiAnagraficiVettore = (DatiAnagraficiVettore) o;
    return Objects.equals(this.idFiscaleIva, datiAnagraficiVettore.idFiscaleIva) &&
        Objects.equals(this.codiceFiscale, datiAnagraficiVettore.codiceFiscale) &&
        Objects.equals(this.anagrafica, datiAnagraficiVettore.anagrafica) &&
        Objects.equals(this.numeroLicenzaGuida, datiAnagraficiVettore.numeroLicenzaGuida);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(idFiscaleIva, codiceFiscale, anagrafica, numeroLicenzaGuida);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatiAnagraficiVettore {\n");
    sb.append("    idFiscaleIva: ").append(toIndentedString(idFiscaleIva)).append("\n");
    sb.append("    codiceFiscale: ").append(toIndentedString(codiceFiscale)).append("\n");
    sb.append("    anagrafica: ").append(toIndentedString(anagrafica)).append("\n");
    sb.append("    numeroLicenzaGuida: ").append(toIndentedString(numeroLicenzaGuida)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id_fiscale_iva", "codice_fiscale", "anagrafica", "numero_licenza_guida"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DatiAnagraficiVettore
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DatiAnagraficiVettore.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DatiAnagraficiVettore is not found in the empty JSON string", DatiAnagraficiVettore.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DatiAnagraficiVettore.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DatiAnagraficiVettore` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `id_fiscale_iva`
      if (jsonObj.get("id_fiscale_iva") != null && !jsonObj.get("id_fiscale_iva").isJsonNull()) {
        IdFiscaleIVA.validateJsonElement(jsonObj.get("id_fiscale_iva"));
      }
      if ((jsonObj.get("codice_fiscale") != null && !jsonObj.get("codice_fiscale").isJsonNull()) && !jsonObj.get("codice_fiscale").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `codice_fiscale` to be a primitive type in the JSON string but got `%s`", jsonObj.get("codice_fiscale").toString()));
      }
      // validate the optional field `anagrafica`
      if (jsonObj.get("anagrafica") != null && !jsonObj.get("anagrafica").isJsonNull()) {
        Anagrafica.validateJsonElement(jsonObj.get("anagrafica"));
      }
      if ((jsonObj.get("numero_licenza_guida") != null && !jsonObj.get("numero_licenza_guida").isJsonNull()) && !jsonObj.get("numero_licenza_guida").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `numero_licenza_guida` to be a primitive type in the JSON string but got `%s`", jsonObj.get("numero_licenza_guida").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DatiAnagraficiVettore.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DatiAnagraficiVettore' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DatiAnagraficiVettore> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DatiAnagraficiVettore.class));

       return (TypeAdapter<T>) new TypeAdapter<DatiAnagraficiVettore>() {
           @Override
           public void write(JsonWriter out, DatiAnagraficiVettore value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DatiAnagraficiVettore read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DatiAnagraficiVettore given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DatiAnagraficiVettore
   * @throws IOException if the JSON string is invalid with respect to DatiAnagraficiVettore
   */
  public static DatiAnagraficiVettore fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DatiAnagraficiVettore.class);
  }

  /**
   * Convert an instance of DatiAnagraficiVettore to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

