/*
 * Invoicetronic API
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: info@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.invoicetronic.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.invoicetronic.sdk.JSON;

/**
 * IdFiscaleIVA
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-07T10:24:03.366361Z[Etc/UTC]", comments = "Generator version: 7.18.0")
public class IdFiscaleIVA implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID_PAESE = "id_paese";
  @SerializedName(SERIALIZED_NAME_ID_PAESE)
  @javax.annotation.Nullable
  private String idPaese;

  public static final String SERIALIZED_NAME_ID_CODICE = "id_codice";
  @SerializedName(SERIALIZED_NAME_ID_CODICE)
  @javax.annotation.Nullable
  private String idCodice;

  public IdFiscaleIVA() {
  }

  public IdFiscaleIVA idPaese(@javax.annotation.Nullable String idPaese) {
    this.idPaese = idPaese;
    return this;
  }

  /**
   * Get idPaese
   * @return idPaese
   */
  @javax.annotation.Nullable
  public String getIdPaese() {
    return idPaese;
  }

  public void setIdPaese(@javax.annotation.Nullable String idPaese) {
    this.idPaese = idPaese;
  }


  public IdFiscaleIVA idCodice(@javax.annotation.Nullable String idCodice) {
    this.idCodice = idCodice;
    return this;
  }

  /**
   * Get idCodice
   * @return idCodice
   */
  @javax.annotation.Nullable
  public String getIdCodice() {
    return idCodice;
  }

  public void setIdCodice(@javax.annotation.Nullable String idCodice) {
    this.idCodice = idCodice;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdFiscaleIVA idFiscaleIVA = (IdFiscaleIVA) o;
    return Objects.equals(this.idPaese, idFiscaleIVA.idPaese) &&
        Objects.equals(this.idCodice, idFiscaleIVA.idCodice);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(idPaese, idCodice);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdFiscaleIVA {\n");
    sb.append("    idPaese: ").append(toIndentedString(idPaese)).append("\n");
    sb.append("    idCodice: ").append(toIndentedString(idCodice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id_paese", "id_codice"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to IdFiscaleIVA
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IdFiscaleIVA.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in IdFiscaleIVA is not found in the empty JSON string", IdFiscaleIVA.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!IdFiscaleIVA.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `IdFiscaleIVA` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id_paese") != null && !jsonObj.get("id_paese").isJsonNull()) && !jsonObj.get("id_paese").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id_paese` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id_paese").toString()));
      }
      if ((jsonObj.get("id_codice") != null && !jsonObj.get("id_codice").isJsonNull()) && !jsonObj.get("id_codice").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id_codice` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id_codice").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IdFiscaleIVA.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IdFiscaleIVA' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IdFiscaleIVA> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IdFiscaleIVA.class));

       return (TypeAdapter<T>) new TypeAdapter<IdFiscaleIVA>() {
           @Override
           public void write(JsonWriter out, IdFiscaleIVA value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IdFiscaleIVA read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of IdFiscaleIVA given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of IdFiscaleIVA
   * @throws IOException if the JSON string is invalid with respect to IdFiscaleIVA
   */
  public static IdFiscaleIVA fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IdFiscaleIVA.class);
  }

  /**
   * Convert an instance of IdFiscaleIVA to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

