/*
 * Italian eInvoice API
 * The Italian eInvoice API is a RESTful API that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed by Invoicetronic to be simple and easy to use, abstracting away SDI complexity while still providing complete control over the invoice send/receive process. The API also provides advanced features and a rich toolchain, such as invoice validation, multiple upload methods, webhooks, event logs, CORS support, client SDKs for commonly used languages, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.Anagrafica;
import org.openapitools.client.model.IdFiscaleIVA;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DatiAnagraficiCedentePrestatore
 */
public class DatiAnagraficiCedentePrestatoreTest {
    private final DatiAnagraficiCedentePrestatore model = new DatiAnagraficiCedentePrestatore();

    /**
     * Model tests for DatiAnagraficiCedentePrestatore
     */
    @Test
    public void testDatiAnagraficiCedentePrestatore() {
        // TODO: test DatiAnagraficiCedentePrestatore
    }

    /**
     * Test the property 'idFiscaleIva'
     */
    @Test
    public void idFiscaleIvaTest() {
        // TODO: test idFiscaleIva
    }

    /**
     * Test the property 'codiceFiscale'
     */
    @Test
    public void codiceFiscaleTest() {
        // TODO: test codiceFiscale
    }

    /**
     * Test the property 'anagrafica'
     */
    @Test
    public void anagraficaTest() {
        // TODO: test anagrafica
    }

    /**
     * Test the property 'alboProfessionale'
     */
    @Test
    public void alboProfessionaleTest() {
        // TODO: test alboProfessionale
    }

    /**
     * Test the property 'provinciaAlbo'
     */
    @Test
    public void provinciaAlboTest() {
        // TODO: test provinciaAlbo
    }

    /**
     * Test the property 'numeroIscrizioneAlbo'
     */
    @Test
    public void numeroIscrizioneAlboTest() {
        // TODO: test numeroIscrizioneAlbo
    }

    /**
     * Test the property 'dataIscrizioneAlbo'
     */
    @Test
    public void dataIscrizioneAlboTest() {
        // TODO: test dataIscrizioneAlbo
    }

    /**
     * Test the property 'regimeFiscale'
     */
    @Test
    public void regimeFiscaleTest() {
        // TODO: test regimeFiscale
    }

}
