/*
 * Invoicetronic API
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: info@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.invoicetronic.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Anagrafica
 */
public class AnagraficaTest {
    private final Anagrafica model = new Anagrafica();

    /**
     * Model tests for Anagrafica
     */
    @Test
    public void testAnagrafica() {
        // TODO: test Anagrafica
    }

    /**
     * Test the property 'denominazione'
     */
    @Test
    public void denominazioneTest() {
        // TODO: test denominazione
    }

    /**
     * Test the property 'nome'
     */
    @Test
    public void nomeTest() {
        // TODO: test nome
    }

    /**
     * Test the property 'cognome'
     */
    @Test
    public void cognomeTest() {
        // TODO: test cognome
    }

    /**
     * Test the property 'titolo'
     */
    @Test
    public void titoloTest() {
        // TODO: test titolo
    }

    /**
     * Test the property 'codEori'
     */
    @Test
    public void codEoriTest() {
        // TODO: test codEori
    }

}
