/*
 * Invoicetronic API
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: info@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.invoicetronic.sdk.api;

import com.invoicetronic.sdk.ApiCallback;
import com.invoicetronic.sdk.ApiClient;
import com.invoicetronic.sdk.ApiException;
import com.invoicetronic.sdk.ApiResponse;
import com.invoicetronic.sdk.Configuration;
import com.invoicetronic.sdk.Pair;
import com.invoicetronic.sdk.ProgressRequestBody;
import com.invoicetronic.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.time.OffsetDateTime;
import com.invoicetronic.sdk.model.ProblemDetails;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ExportApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ExportApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ExportApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for exportGet
     * @param type  (optional, default to Both)
     * @param companyId Company id (optional)
     * @param year  (optional)
     * @param month  (optional)
     * @param quarter  (optional)
     * @param documentDateFrom UTC ISO 8601 (2024-11-29T12:34:56Z) (optional)
     * @param documentDateTo UTC ISO 8601 (2024-11-29T12:34:56Z) (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 204 </td><td> No Content </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call exportGetCall(@javax.annotation.Nullable String type, @javax.annotation.Nullable Integer companyId, @javax.annotation.Nullable Integer year, @javax.annotation.Nullable Integer month, @javax.annotation.Nullable Integer quarter, @javax.annotation.Nullable OffsetDateTime documentDateFrom, @javax.annotation.Nullable OffsetDateTime documentDateTo, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/export";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (type != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("type", type));
        }

        if (companyId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("company_id", companyId));
        }

        if (year != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("year", year));
        }

        if (month != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("month", month));
        }

        if (quarter != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("quarter", quarter));
        }

        if (documentDateFrom != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("document_date_from", documentDateFrom));
        }

        if (documentDateTo != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("document_date_to", documentDateTo));
        }

        final String[] localVarAccepts = {
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "Basic" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call exportGetValidateBeforeCall(@javax.annotation.Nullable String type, @javax.annotation.Nullable Integer companyId, @javax.annotation.Nullable Integer year, @javax.annotation.Nullable Integer month, @javax.annotation.Nullable Integer quarter, @javax.annotation.Nullable OffsetDateTime documentDateFrom, @javax.annotation.Nullable OffsetDateTime documentDateTo, final ApiCallback _callback) throws ApiException {
        return exportGetCall(type, companyId, year, month, quarter, documentDateFrom, documentDateTo, _callback);

    }

    /**
     * Export invoices as a ZIP archive
     * Export invoices as a ZIP archive of FatturaPA XML files, suitable for import into accounting software (TeamSystem, Zucchetti, etc.).  **Sent invoices** are only included when they have reached a definitive state (e.g., &#x60;Consegnato&#x60; for private recipients, &#x60;AccettatoDalDestinatario&#x60;, &#x60;DecorrenzaTermini&#x60;, etc.). Invoices still being processed by SDI are excluded.  **Received invoices** are always included. Unread invoices are automatically marked as read and counted as operations.  ### Period filters  You can filter by period using either: - &#x60;year&#x60; + &#x60;month&#x60; (e.g., &#x60;year&#x3D;2026&amp;month&#x3D;3&#x60; for March 2026) - &#x60;year&#x60; + &#x60;quarter&#x60; (e.g., &#x60;year&#x3D;2026&amp;quarter&#x3D;1&#x60; for Q1 Jan-Mar) - &#x60;document_date_from&#x60; / &#x60;document_date_to&#x60; for a custom date range  These options are mutually exclusive. The &#x60;year&#x60; parameter alone is not valid and requires either &#x60;month&#x60; or &#x60;quarter&#x60;.  ### Response  Returns &#x60;200&#x60; with a ZIP archive, or &#x60;204 No Content&#x60; if no invoices match the given filters. Files in the archive are organized by company VAT number (&#x60;{vat}/send/&#x60;, &#x60;{vat}/receive/&#x60;).  ### Rate limiting  This endpoint has a dedicated rate limit: only one export request per user can be processed at a time. Concurrent requests will receive a &#x60;429 Too Many Requests&#x60; response.
     * @param type  (optional, default to Both)
     * @param companyId Company id (optional)
     * @param year  (optional)
     * @param month  (optional)
     * @param quarter  (optional)
     * @param documentDateFrom UTC ISO 8601 (2024-11-29T12:34:56Z) (optional)
     * @param documentDateTo UTC ISO 8601 (2024-11-29T12:34:56Z) (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 204 </td><td> No Content </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public void exportGet(@javax.annotation.Nullable String type, @javax.annotation.Nullable Integer companyId, @javax.annotation.Nullable Integer year, @javax.annotation.Nullable Integer month, @javax.annotation.Nullable Integer quarter, @javax.annotation.Nullable OffsetDateTime documentDateFrom, @javax.annotation.Nullable OffsetDateTime documentDateTo) throws ApiException {
        exportGetWithHttpInfo(type, companyId, year, month, quarter, documentDateFrom, documentDateTo);
    }

    /**
     * Export invoices as a ZIP archive
     * Export invoices as a ZIP archive of FatturaPA XML files, suitable for import into accounting software (TeamSystem, Zucchetti, etc.).  **Sent invoices** are only included when they have reached a definitive state (e.g., &#x60;Consegnato&#x60; for private recipients, &#x60;AccettatoDalDestinatario&#x60;, &#x60;DecorrenzaTermini&#x60;, etc.). Invoices still being processed by SDI are excluded.  **Received invoices** are always included. Unread invoices are automatically marked as read and counted as operations.  ### Period filters  You can filter by period using either: - &#x60;year&#x60; + &#x60;month&#x60; (e.g., &#x60;year&#x3D;2026&amp;month&#x3D;3&#x60; for March 2026) - &#x60;year&#x60; + &#x60;quarter&#x60; (e.g., &#x60;year&#x3D;2026&amp;quarter&#x3D;1&#x60; for Q1 Jan-Mar) - &#x60;document_date_from&#x60; / &#x60;document_date_to&#x60; for a custom date range  These options are mutually exclusive. The &#x60;year&#x60; parameter alone is not valid and requires either &#x60;month&#x60; or &#x60;quarter&#x60;.  ### Response  Returns &#x60;200&#x60; with a ZIP archive, or &#x60;204 No Content&#x60; if no invoices match the given filters. Files in the archive are organized by company VAT number (&#x60;{vat}/send/&#x60;, &#x60;{vat}/receive/&#x60;).  ### Rate limiting  This endpoint has a dedicated rate limit: only one export request per user can be processed at a time. Concurrent requests will receive a &#x60;429 Too Many Requests&#x60; response.
     * @param type  (optional, default to Both)
     * @param companyId Company id (optional)
     * @param year  (optional)
     * @param month  (optional)
     * @param quarter  (optional)
     * @param documentDateFrom UTC ISO 8601 (2024-11-29T12:34:56Z) (optional)
     * @param documentDateTo UTC ISO 8601 (2024-11-29T12:34:56Z) (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 204 </td><td> No Content </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> exportGetWithHttpInfo(@javax.annotation.Nullable String type, @javax.annotation.Nullable Integer companyId, @javax.annotation.Nullable Integer year, @javax.annotation.Nullable Integer month, @javax.annotation.Nullable Integer quarter, @javax.annotation.Nullable OffsetDateTime documentDateFrom, @javax.annotation.Nullable OffsetDateTime documentDateTo) throws ApiException {
        okhttp3.Call localVarCall = exportGetValidateBeforeCall(type, companyId, year, month, quarter, documentDateFrom, documentDateTo, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Export invoices as a ZIP archive (asynchronously)
     * Export invoices as a ZIP archive of FatturaPA XML files, suitable for import into accounting software (TeamSystem, Zucchetti, etc.).  **Sent invoices** are only included when they have reached a definitive state (e.g., &#x60;Consegnato&#x60; for private recipients, &#x60;AccettatoDalDestinatario&#x60;, &#x60;DecorrenzaTermini&#x60;, etc.). Invoices still being processed by SDI are excluded.  **Received invoices** are always included. Unread invoices are automatically marked as read and counted as operations.  ### Period filters  You can filter by period using either: - &#x60;year&#x60; + &#x60;month&#x60; (e.g., &#x60;year&#x3D;2026&amp;month&#x3D;3&#x60; for March 2026) - &#x60;year&#x60; + &#x60;quarter&#x60; (e.g., &#x60;year&#x3D;2026&amp;quarter&#x3D;1&#x60; for Q1 Jan-Mar) - &#x60;document_date_from&#x60; / &#x60;document_date_to&#x60; for a custom date range  These options are mutually exclusive. The &#x60;year&#x60; parameter alone is not valid and requires either &#x60;month&#x60; or &#x60;quarter&#x60;.  ### Response  Returns &#x60;200&#x60; with a ZIP archive, or &#x60;204 No Content&#x60; if no invoices match the given filters. Files in the archive are organized by company VAT number (&#x60;{vat}/send/&#x60;, &#x60;{vat}/receive/&#x60;).  ### Rate limiting  This endpoint has a dedicated rate limit: only one export request per user can be processed at a time. Concurrent requests will receive a &#x60;429 Too Many Requests&#x60; response.
     * @param type  (optional, default to Both)
     * @param companyId Company id (optional)
     * @param year  (optional)
     * @param month  (optional)
     * @param quarter  (optional)
     * @param documentDateFrom UTC ISO 8601 (2024-11-29T12:34:56Z) (optional)
     * @param documentDateTo UTC ISO 8601 (2024-11-29T12:34:56Z) (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 204 </td><td> No Content </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call exportGetAsync(@javax.annotation.Nullable String type, @javax.annotation.Nullable Integer companyId, @javax.annotation.Nullable Integer year, @javax.annotation.Nullable Integer month, @javax.annotation.Nullable Integer quarter, @javax.annotation.Nullable OffsetDateTime documentDateFrom, @javax.annotation.Nullable OffsetDateTime documentDateTo, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = exportGetValidateBeforeCall(type, companyId, year, month, quarter, documentDateFrom, documentDateTo, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
